### ISSUE TITLE
認証周りを構築した際にどのような手順で構築したか？を整理する

### ISSUE THREAD

**Issue by sakamoto-family-smile** [sakamoto-family-smile/line_sakamomo_family_api#53]
# 概要

認証周り（ログイン機能）を構築して、バックエンド側のrunをガードする対応を入れているが、
この環境を高築する際にどのような手順を実施したか？を整理して、フロー化する。
※readmeに手順を記載するため。

# 成果物

フローやステップがまとまったドキュメントができていること

**Comment by sakamoto-family-smile** [comment]
#16 でコメントがいくつかkaitearu

**Comment by sakamoto-family-smile** [comment]
# 現状の構成

* Idpでwebフロントからログイン認証を行い、ログインができていれば、ユーザーごとのtokenが発行される
* そのtokenをauthorization-headerに付与して、LBのエンドポイントにアクセスする
* tokenが妥当かをIap側で判断し、問題なければ、バックエンドのrunにルーティングされる

**Comment by sakamoto-family-smile** [comment]
前も悩んでたと思うが、identity platformで取得したトークンをidentity aware proxy側でどうやってトークン確認をしているんだろ？
※何かしらの紐付けをGCP上でしているはずなんだけど・・

**Comment by sakamoto-family-smile** [comment]
LBでHTTPS通信を許可するために証明書とドメイン取得もしている
Cloud Domains

**Comment by sakamoto-family-smile** [comment]
新しくGCPを作って、そこで環境作ってみよう

**Comment by sakamoto-family-smile** [comment]
# 対応ステップ

対応ステップを大枠整理する。

* Service Accountの構築（必要な権限を付与）
* EDINET API KEYの取得
* OpenAI API  KEYの取得（なくてもよいかも）
* .envファイルの作成
* CloudRunの構築（フロントエンド、バックエンド）
* CloudRun Jobsの構築（パイプライン部分）
* BigQueryのデータソース作成（パイプライン利用）
* Identity Platformの構築（Email/Password）
* Identity Aware Proxyの構築
  * https://zenn.dev/google_cloud_jp/articles/cloudrun-iap-idp を参考にする 
* Load Balancingの構築（SGの設定、Firewallの設定）
* Cloud DNSの設定（バックエンドに紐づける？）

#  最終的には

terraform化して、残したい

**Comment by sakamoto-family-smile** [comment]
SAはちょっと分割したいな。今は、SAになんでもかんでも権限付与している。

* デプロイ用のSA
* 各CloudRunに必要な権限をまとめたSA
* その他

とかで分けるか

**Comment by sakamoto-family-smile** [comment]
# 事前準備

* GCP プロジェクトの作成
* google cloud CLIの導入

# Service Accountの構築

* service-deployをデプロイ用のSAとして生成。
  * 権限
    * 編集者（roles/editor） 
    * run管理者（roles/run.admin）
  * gcloud CLIに、service-deployのSAを新規プロジェクトに対して、紐づけるように設定
    * 過程で、compute apiを有効化 
* backendに設定するSAを生成
  * 権限
    * roles/editor
    * Storage オブジェクト管理者
* frontendに設定するSAを生成
  * 権限
    * roles/editor  

```
gcloud config configurations create <任意の名前>
gcloud config set account <SA名>
gcloud config set project <project-ID>
gcloud config set compute/region asia-northeast1
gcloud config set compute/zone asia-northeast1-a
```

※SAについては、terraformで自動構築するスクリプトを実装した

**Comment by sakamoto-family-smile** [comment]
# CloudRunの構築

★はterraform対応予定

* make push_imageを行ったがエラーとなった
```
denied: Artifact Registry API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=xx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
* ★sakamomo-family-apiのリポジトリを新規作成
  * artifact registry apiを有効化 
* ★firestoreの構築
  * firestore apiの有効化（console上なら、データベース作成時に有効化されそう） 
  * データベース名は(default)とすること。ここを変えると、現状のコードでは動かなくなるはず（明示的にデータベース名を指定すればいけるかも）
* ★GCSバケットの生成
  * sakamomo_family_apiのバケットを生成 
* ★vertexai apiを有効化する（google cloud console上で）
* backend
  * make build -> make push_imageを実施
  * make deploy_apiを実行（その際、run apiを有効化）
* frontend
  * config.jsonの作成、修正
     * apiKey: identity platformのAPI keyを設定（idpのアプリケーション設定の詳細から取得）
     * authDomain: identity platformのauthDomainを設定（idpのアプリケーション設定の詳細から取得）
     * databaseURL: 空文字
     * storageBucket: 空文字
  * iap_config.jsonの作成、修正
     * CLIENT_ID:
     * CLIENT_SECRET: 
     * BACKEND_URL:  backendのrunの前段にいるLBのURLを設定（CloudDNSで構築したドメイン）
  * make build -> make push_imageを実施
  * make deploy_runを実行

# 参考

https://cloud.google.com/run/docs/authenticating/public?hl=ja#gcloud
https://cloud.google.com/identity-platform/docs/use-rest-api?hl=ja
https://cloud.google.com/run/docs/securing/ingress?hl=ja#set_ingress

**Comment by sakamoto-family-smile** [comment]
# CloudRun Jobsの構築（パイプライン部分）

* make build -> make push_image
* ×Job Service Accountの生成（一旦、service-deployのSAと同様とする。これは不要そう）
* ★BigQueryのEDINET情報を保存するテーブルの作成（[GCP Project ID].family_data.edinet_document_metadata）
* make deploy_job -> make run_job
  * スキーマがないと言われて、エラーになった（スキーマを事前に定義したほうがよさそう） 
  * 初回生成時はdeleteのクエリを実施しないようにするとよさそう
  * jobのコードを修正（PRを上げる）
* make register_job_scheduler
  * cloudscheduler apiがONになる

**Comment by sakamoto-family-smile** [comment]
# Identity Platformの構築（Email/Password）

* ★identity platformを有効化（google cloud console上）
* プロバイダを追加する（google cloud console上）
  * メール/パスワード 
* 任意のユーザーを追加する

**Comment by sakamoto-family-smile** [comment]
# Identity Aware Proxyの構築

* ★APIを有効にする（google cloud console上）
* 同意画面を構成（google cloud console上）
  * oauth認証画面を構築

**Comment by sakamoto-family-smile** [comment]
# Load Balancingの構築（SGの設定、Firewallの設定）

* Cloud Domainsを使って、ドメインを準備する（HTTPS通信とするため）
  * ★cloud domains apiを有効にする
  * ★cloud dns apiを有効にする
  * cloud domains経由で、ドメインを作成する（google cloud consoleより）
  * 生成したドメインに対して、activation処理を行う（メールで対応する。設定したEメールアドレス宛に、verifyのメールが飛んでくるので、クリックすれば良い）
* 外部IPアドレスの取得（google cloud console上で実施）
  * この時点ではバックエンドサービスがないため、なし、で設定 
* SSL 証明書リソースを作成
  * https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs?hl=ja
  * ドメインを、cloud domainsで作成したドメインと同様の名前を設定（多分、これであってるはず・・）
  * このタイミングでは、証明書のステータスがprovisioningのままとなる 
* HTTPSロードバランサーの作成
  * https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs?hl=ja#load-balancer
  * 設定
     * アプリケーションロードバランサーを設定
     * インターネット接続（外部）を設定
     * グローバルワークロード
     * グローバル外部アプリケーションロードバランサーを設定
   * フロントエンドの構成
     * 静的IPの設定（なぜかここで作り直した）
     * 証明書を設定（先ほど作ったSSL証明書を設定）
   * バックエンドの構成
     * バックエンドサービスの新規作成
       * サーバーレスネットワークエンドポイントグループを選択し、新規作成
       * CDNは無効
       * ロギングは有効化
       * ★一旦、デフォルトのセキュリティポリシーを設定（後でポリシーを確認して、修正検討）
     * サーバーレスネットワークエンドポイントグループの作成
       * リージョンを東京
       * CloudRunを指定し、sakamomo-family-apiのbackendのCloudRunを指定        
   * ルーティングルール
     * ★一旦、全パスで設定（特定パスのみとし、他パスは別へルーティングしたい）
* DNSの設定
   * 取得したドメインとLBの紐付け
     * https://cloud.google.com/load-balancing/docs/https/setup-global-ext-https-serverless?hl=ja#update_dns
     * ドメイン画面から、LBのIPをwww, @に対して設定 
* LBのバックエンドとIAPの設定
   * IAPの画面より設定
   * IAPの有効化
     * 対象となるbackendのIAPが有効化されているかを確認   
   * CLIEND_ID, CLIENT_SECRETの確認（runのbackendのiap_config.jsonに設定）
     * OAuth構成に移動する、を選択すると、CLIENT_ID, CLIENT_SECRETが確認可能（ただし、IAPがONだと見れない） 
   * 「承認には外部 ID を使用します」を開始する
     * 準備したIDPのEmail/Passwordを選択
     * ログインページを作成、を選択（自動でrun上にログインページが作成される。今回は利用しない）  
   * 設定より、HTTPオプションを有効にする（これは、python clientの場合は不要だが、javascript経由のアクセスの場合は、CORS対策として必要）

## 参考

https://cloud.google.com/load-balancing/docs/https/setup-global-ext-https-serverless?hl=ja
https://zenn.dev/google_cloud_jp/articles/cloudrun-itg-alb
https://zenn.dev/google_cloud_jp/articles/cloudrun-iap

cloudrun integrationsを利用したLB設定はできなくなっている（2024年10月以降）

**Comment by sakamoto-family-smile** [comment]
今回はLBの設定などをCloudRun Integrationsを使って試してみよう

**Comment by sakamoto-family-smile** [comment]
https://cloud.google.com/run/docs/integrate/custom-domain-load-balancer?hl=ja
cloudrun integrationはなくなってた・・涙

**Comment by sakamoto-family-smile** [comment]
あれ、front側のrunが認証が必要になっている（IAM権限が必要）
↓
https://cloud.google.com/run/docs/authenticating/public?hl=ja#gcloud
runの管理者権限をdeploy用のSAに設定

**Comment by sakamoto-family-smile** [comment]
iap_config.jsonのCLIENT_ID、CLIENT_SECRETが使われてないような？

**Comment by sakamoto-family-smile** [comment]
https://cloud.google.com/load-balancing/docs/https/setup-global-ext-https-serverless?hl=ja#update_dns
ドメインをLBと紐づけないといけない

**Comment by sakamoto-family-smile** [comment]
https://cloud.google.com/load-balancing/docs/https/https-logging-monitoring?hl=ja#view_logs
LBのログは上記を参考にして、見る

**Comment by sakamoto-family-smile** [comment]
ログインはできるようになっていそう
うーむ、、ヘルスチェックが通らない・・（フロントからバックエンドにリクエストを投げている）

```
Traceback (most recent call last):
  File "/work/app/ui.py", line 151, in financial_report_analysis_page
    backend_requester.request_health_check(token=st.session_state[TOKEN_KEY])
  File "/work/app/backend_util.py", line 16, in request_health_check
    resp = requests.request("GET", url, headers={"Authorization": "Bearer {}".format(token)})
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sakamomo-family-service.com', port=443): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x3e04158f1180>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by sakamoto-family-smile** [comment]
あれ、loggingみると、アプリケーションロードバランサーがいない・・

**Comment by sakamoto-family-smile** [comment]
あ、証明書のステータスがFAILED_NOT_VISIBLEになってる。なんで？

**Comment by sakamoto-family-smile** [comment]
https://cloud.google.com/load-balancing/docs/ssl-certificates/troubleshooting?hl=ja#domain-status
上記を見て、調査する

**Comment by sakamoto-family-smile** [comment]
DNSとIPの紐付けをついさっきやったからな、、一旦まちかもしれない。

**Comment by sakamoto-family-smile** [comment]
お、証明書がOKになった。
ただし、エラーは継続。別のエラーになった。

```
Traceback (most recent call last):
  File "/work/app/ui.py", line 151, in financial_report_analysis_page
    backend_requester.request_health_check(token=st.session_state[TOKEN_KEY])
  File "/work/app/backend_util.py", line 18, in request_health_check
    raise Exception(
Exception: Bad response from application: 401 / {'www-authenticate': 'Bearer error="invalid_token" error_description="The access token could not be verified"', 'date': 'Fri, 27 Dec 2024 04:32:51 GMT', 'content-type': 'text/html; charset=UTF-8', 'server': 'Google Frontend', 'Content-Length': '300', 'via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'} / '\n<html><head>\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>401 Unauthorized</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Unauthorized</h1>\n<h2>Your client does not have permission to the requested URL <code>/health</code>.</h2>\n<h2></h2>\n</body></html>\n'
```

**Comment by sakamoto-family-smile** [comment]
下記のエラーっぽい。

```
The request was not authorized to invoke this service. Read more at https://cloud.google.com/run/docs/securing/authenticating Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#401
```

**Comment by sakamoto-family-smile** [comment]
本当はrun側もSAを作って、権限を付与すべきだな。
※今は、SAを指定しないでデプロイしているため、デフォルトの権限が付与されてそう（roles/editor相当になっている）

**Comment by sakamoto-family-smile** [comment]
あ、runの権限かも。
すでに動いているrunだと、「未認証を許可 | 内部 + ロード バランシング」の設定になっている

↓

これはmakefile側のコマンドで対応すべき。修正する。

**Comment by sakamoto-family-smile** [comment]
あー、多分、firestoreがないんだ。設定する。

**Comment by sakamoto-family-smile** [comment]
手順がだいぶ複雑になってきた。

* いくつかをmakefileに入れて、セットアップを自動化したい（BQのテーブル作成、firestoreの作成など）
* terraform化をする（これは一旦後で良い）

**Comment by sakamoto-family-smile** [comment]
search_company.sqlで、データセットが直打ちになっている
これはどうするかなぁ。
セットアップとして、family_dataのデータセットを作るのを強制とするか。

**Comment by sakamoto-family-smile** [comment]
```
 "message": "102889567062-compute@developer.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist).",
```

あー、gcsの権限不足か・・。
やはり、runに渡すSAはちゃんと作った方が良い。

**Comment by sakamoto-family-smile** [comment]
いや、バケットがないのか？

**Comment by sakamoto-family-smile** [comment]
そうか、、gcsバケットって、プロジェクト横断でユニークだから、すでに手元で作っているバケット名がsakamomo_family_apiなので、同じ名前使えないのか・・。

バケット名は、環境変数なりで与えるようにしないとダメだな。
※他プロジェクトのバケットは、バケットに対するアクセス権をバケットがあるプロジェクト上で権限設定が必要

↓

ローカルで修正済み

**Comment by sakamoto-family-smile** [comment]
お、下記のエラーは、vertexaiを有効化すれば良さそう

```
403 Vertex AI API has not been used in project sakamomo-family-service before or it is disabled
```

**Comment by sakamoto-family-smile** [comment]
ふぅ、やっと動いた・・。
ある程度、セットアップを自動化して、手動部分だけをドキュメントにまとめていく。

**Comment by sakamoto-family-smile** [comment]
https://cloud.google.com/docs/terraform/resource-management/export?hl=ja
お、terraform形式でもエクスポートできそう。試してみる
↓
エクスポートされたが、結構な量だな・・。

**Comment by sakamoto-family-smile** [comment]
# 残件

* makeコマンド、terraformで自動化する箇所を自動化していく
* 手動部分をドキュメント（readmeなど）に手順をまとめる
* 再度、上記をもろもろ使って、環境が構築されるかを検証
* PR発行 + マージ

**Comment by sakamoto-family-smile** [comment]
認証と認可（OIDCとOAuth）
https://zenn.dev/tanaka_takeru/articles/b27f90632efe22

**Comment by sakamoto-family-smile** [comment]
OAuth、OIDC、SAMLの違い
https://www.okta.com/jp/identity-101/whats-the-difference-between-oauth-openid-connect-and-saml/

**Comment by sakamoto-family-smile** [comment]
https://cloud.google.com/docs/authentication/token-types?hl=ja
IDPで発行されるIDトークンの有効期限も上記に書いてある。3600秒が最大値（デフォルト）

**Comment by sakamoto-family-smile** [comment]
ドメイン、SSL証明書の必要な理由が微妙に整理できてないかも。
SSL証明書はHTTPS通信にする上で必須だけど、ドメインは？
※まぁ、オレオレ証明書を回避するなら、必須になるか。
↓
SSL証明書作成時にドメインが必須なので、ドメインも必要。

**Comment by sakamoto-family-smile** [comment]
構築手順をざっと下記でまとめた
https://yard.tips/sakamomo554101/articles/cm4gzi7ky0001b7bszi7q6zvr
