### ISSUE TITLE
Agentに検索機能（ツール）を入れる

### ISSUE THREAD

**Issue by sakamoto-family-smile** [sakamoto-family-smile/line_sakamomo_family_api#8]
serpapiがいいけど、高いので、他を検討したい

**Comment by sakamoto-family-smile** [comment]
google-searchを入れてみたが、下記のエラー。
API_KEYとかが問題？

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 68, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/work/app/line_api.py", line 24, in <module>
    local_agent = CustomAgent(agent_config=agent_config, logger=logger)
  File "/work/app/agent.py", line 81, in __init__
    tools = self.get_tools(llm=llm)
  File "/work/app/agent.py", line 126, in get_tools
    tools = load_tools(["openweathermap-api", "google-search"], llm)
  File "/usr/local/lib/python3.10/site-packages/langchain/agents/load_tools.py", line 681, in load_tools
    tool = _get_tool_func(**sub_kwargs)
  File "/usr/local/lib/python3.10/site-packages/langchain/agents/load_tools.py", line 268, in _get_google_search
    return GoogleSearchRun(api_wrapper=GoogleSearchAPIWrapper(**kwargs))
  File "/usr/local/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 183, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for GoogleSearchAPIWrapper
```

**Comment by sakamoto-family-smile** [comment]
あ、よくみたら、エラーログがcloudrun側に出てた

```
Did not find google_cse_id, please add an environment variable `GOOGLE_CSE_ID` which contains it, or pass `google_cse_id` as a named parameter. (type=value_error)
```

**Comment by sakamoto-family-smile** [comment]
完了
